DROP TABLE IF EXISTS Entry;
DROP TABLE IF EXISTS SubTopic;
DROP TABLE IF EXISTS Topic;

CREATE TABLE Topic
(
    id SERIAL NOT NULL PRIMARY KEY ,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE SubTopic
(
    id SERIAL NOT NULL PRIMARY KEY ,
    name VARCHAR(255) NOT NULL UNIQUE ,
    icon CHAR(1)      NOT NULL
);

CREATE TABLE Entry (
    id SERIAL NOT NULL PRIMARY KEY,
    topic_id INT NOT NULL REFERENCES Topic(id),
    subtopic_id INT NOT NULL REFERENCES SubTopic(id),
    amount DECIMAL NOT NULL
)